id: I9052EF69
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T11:45:00+00:00'
last_modified: '2022-06-16T04:38:16.393909+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23151
  title: གསུང་འབུམ། བློ་བཟང་ཚུལ་ཁྲིམས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    9C48:
      image_group_id: I1KG8795
      title: Volume 1 of gsung 'bum/_blo bzang tshul khrims/
      total_pages: 714
      order: 1
      base_file: 9C48.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
